# Generated by Django 4.1.2 on 2023-03-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
