# Generated by Django 4.1.2 on 2023-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room", old_name="Participants", new_name="participants",
        ),
    ]
