# Generated by Django 4.1.2 on 2023-03-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_participants_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["-updated", "-created"]},
        ),
    ]
