# Generated by Django 4.1.2 on 2023-04-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_message_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["updated", "created"]},
        ),
    ]
