# Generated by Django 4.1.2 on 2023-04-05 17:34

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", base.managers.UserManager()),],
        ),
    ]
